complete_images = "Phytoplankton_Images/"
complete_csv = "/content/gdrive/My Drive/Colab Notebooks/csv/complete_updated.csv"
output_file_name = ""
tb_log_parent_dir = "logs/"
tb_log_current_dir = ""
