complete_images = "/scratch/Phytoplankton_Images/"
complete_csv = "/nfs/stak/users/jacomatt/Thesis/data/complete_updated.csv"
output_file_name = ""
tb_log_parent_dir = "logs/"
tb_log_current_dir = ""
